src/web/ESE.WebApp.MVC/Controllers/CartController.cs
using ESE.WebApp.MVC.Models;
using ESE.WebApp.MVC.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace ESE.WebApp.MVC.Controllers
{
    public class CartController : MainController
    { 
        private readonly IShoppingBffService _shoppingBffService;

        public CartController(IShoppingBffService shoppingBffService)
        {
            _shoppingBffService = shoppingBffService;
        }

        [Route("cart")]
        public async Task<IActionResult> Index()
        {
            return View(await _shoppingBffService.GetCart());
        }

        [HttpPost]
        [Route("cart/add-item")]
        public async Task<IActionResult> AddCartItem(ItemCartViewModel itemProduct)
        {
            var response = await _shoppingBffService.AddItemCart(itemProduct);

            if (HasErrorsResponse(response)) return View("Index", await _shoppingBffService.GetCart());

            return RedirectToAction("Index");
        }

        [HttpPost]
        [Route("cart/update-item")]
        public async Task<IActionResult> UpdateItemCart(Guid productId, int quantity)
        {
            var itemProduct = new ItemCartViewModel { ProductId = productId, Quantity = quantity };
            var response = await _shoppingBffService.UpdateItemCart(productId, itemProduct);

            if (HasErrorsResponse(response)) return View("Index", await _shoppingBffService.GetCart());

            return RedirectToAction("Index");
        }

        [HttpPost]
        [Route("cart/remove-item")]
        public async Task<IActionResult> RemoveItemCart(Guid productId)
        {
            var response = await _shoppingBffService.RemoveItemCart(productId);

            if (HasErrorsResponse(response)) return View("Index", await _shoppingBffService.GetCart());

            return RedirectToAction("Index");
        }

        [HttpPost]
        [Route("cart/apply-voucher")]
        public async Task<IActionResult> ApplyVoucher(string voucherCode)
        {
            var response = await _shoppingBffService.ApplyVoucherCart(voucherCode);

            if (HasErrorsResponse(response)) return View("Index", await _shoppingBffService.GetCart());

            return RedirectToAction("Index");
        }
    }
}

src/web/ESE.WebApp.MVC/Controllers/CatalogController.cs
using ESE.WebApp.MVC.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace ESE.WebApp.MVC.Controllers
{
    public class CatalogController : MainController
    {
        private readonly ICatalogService _catalogService;

        public CatalogController(ICatalogService catalogService)
        {
            _catalogService = catalogService;
        }

        [HttpGet]
        [Route("")]
        [Route("products")]
        public async Task<IActionResult> Index([FromQuery] int ps = 8, [FromQuery] int page = 1, [FromQuery] string q = null)
        {
            var products = await _catalogService.GetAll(ps, page, q);
            ViewBag.Search = q;
            products.ReferenceAction = "Index";

            return View(products);
        }

        [HttpGet]
        [Route("product-details/{id}")]
        public async Task<IActionResult> ProductDetails(Guid id)
        {
            var product = await _catalogService.GetById(id);

            return View(product);
        }
    }
}

src/web/ESE.WebApp.MVC/Extensions/PaginationViewComponent.cs
using ESE.WebApp.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ESE.WebApp.MVC.Extensions
{
    public class PaginationViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(IPagedList modelPagined)
        {
            return View(modelPagined);
        }
    }
}

src/web/ESE.WebApp.MVC/Views/Catalog/Index.cshtml
@using ESE.WebApp.MVC.Extensions
@model PagedViewModel<ProductViewModel>

@{
    ViewData["Title"] = "Todos os produtos";
}

<section>
    <div>
        <div style="background-image: url(images/banners/Template.jpg); height: 100%; background-position: center; background-repeat: no-repeat; background-size: cover">
            <div style="text-align: center;">
                <img src="~/images/banners/EasyStore.png" />
            </div>
        </div>
        <div class="container" style=" padding-top: 20px">
            <div class="row">
                @{
                    foreach (var product in Model.List.OrderBy(p => p.Name))
                    {
                        <div class="col-md-3">
                            <div href="#" class="card card-product-grid">
                                <a asp-controller="Catalog" asp-action="ProductDetails" asp-route-id="@product.Id" class="img-wrap">
                                    <img src="~/images/products/@product.Image" alt="@product.Name">
                                </a>
                                <figcaption class="info-wrap">
                                    <a asp-controller="Catalog" asp-action="ProductDetails" asp-route-id="@product.Id" class="title">
                                        <b> @product.Name</b>
                                    </a>

                                    <small class="card-text">
                                        @this.StockMessage(product.Stock)<br /><br />
                                        @product.Description
                                    </small>
                                </figcaption>
                                <div class="card-footer price mt-1 text-center">
                                    <h3>@this.FormatCurrency(product.Price)</h3>
                                </div>
                            </div>
                        </div>
                    }
                }
            </div>
            <vc:pagination model-pagined="@Model"></vc:pagination>
        </div>
    </div>
</section>

src/web/ESE.WebApp.MVC/Views/Catalog/ProductDetail.cshtml
@using ESE.WebApp.MVC.Extensions
@model ESE.WebApp.MVC.Models.ProductViewModel
@{
    ViewData["Title"] = Model.Name;
}
<section class="section-content padding-y bg container">
    <div class="card">
        <div class="row no-gutters">
            <aside class="col-md-6">
                <article class="gallery-wrap">
                    <div class="img-big-wrap" style="text-align: center">
                        <img src="~/images/produtos/@Model.Image" alt="@Model.Name">
                    </div>
                </article>
            </aside>
            <main class="col-md-6 border-left">
                <article class="content-body">

                    <h2 class="title">@Model.Name</h2>

                    <div class="rating-wrap my-3">
                        <ul class="rating-stars">
                            <li style="width: 80%" class="stars-active">
                                <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </li>
                            <li>
                                <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </li>
                        </ul>
                        <small class="label-rating text-muted">132 avaliações</small>
                        <small class="label-rating text-success"> <i class="fa fa-clipboard-check"></i> 154 peças vendidas</small>
                    </div>

                    <div class="mb-3">
                        <var class="price h4">@Model.Price</var>
                    </div>

                    <h5>@Model.Description</h5><br />
                    <p> @Model.Stock</p>

                    <hr>

                    @{
                        if (Model.Stock > 0)
                        {
                            <div class="form-row">
                                <div class="form-group col-md flex-grow-0">
                                    <label>Quantidade</label>
                                    <div class="input-group input-spinner">
                                        <select class="form-control">
                                            <option value="1">1</option>
                                            <option value="2">2</option>
                                            <option value="3">3</option>
                                            <option value="4">4</option>
                                            <option value="5">5</option>
                                        </select>
                                    </div>
                                </div>

                            </div>
                            <br />
                            <a href="#" class="btn  btn-outline-primary">
                                <span class="text">Adicionar ao carrinho</span> <i class="fas fa-shopping-cart"> &nbsp;</i>
                            </a>

                        }
                    }

                    <a asp-action="Index" class="btn  btn-info">
                        <span class="text">Voltar</span>
                    </a>
                </article>
            </main>
        </div>
    </div>
</section>

src/web/ESE.WebApp.MVC/Views/Catalog/ProductDetails.cshtml
@using ESE.WebApp.MVC.Extensions
@model ESE.WebApp.MVC.Models.ProductViewModel
@{
    ViewData["Title"] = Model.Name;
}
<section class="section-content padding-y bg container">
    <div class="card">
        <div class="row no-gutters">
            <aside class="col-md-6">
                <article class="gallery-wrap">
                    <div class="img-big-wrap" style="text-align: center">
                        <img src="~/images/products/@Model.Image" alt="@Model.Name">
                    </div>
                </article>
            </aside>
            <main class="col-md-6 border-left">
                <article class="content-body">
                    <form asp-controller="Cart" asp-action="AddCartItem" method="post">

                        <input type="hidden" id="ProductId" name="ProductId" value="@Model.Id" />

                        <h2 class="title">@Model.Name</h2>

                        <div class="rating-wrap my-3">
                            <ul class="rating-stars">
                                <li style="width: 80%" class="stars-active">
                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                </li>
                                <li>
                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                </li>
                            </ul>
                            <small class="label-rating text-muted">132 avaliações</small>
                            <small class="label-rating text-success"> <i class="fa fa-clipboard-check"></i> 154 peças vendidas</small>
                        </div>

                        <div class="mb-3">
                            <var class="price h4">@this.FormatCurrency(Model.Price)</var>
                        </div>

                        <h5>@Model.Description</h5><br />
                        <p> @this.StockMessage(Model.Stock)</p>

                        <hr>

                        @{
                            if (Model.Stock > 0)
                            {
                                <div class="form-row">
                                    <div class="form-group col-md flex-grow-0">
                                        <label>Quantidade</label>
                                        <div class="input-group input-spinner">
                                            <select id="Quantity" name="Quantity" class="form-control">
                                                <option value="1">1</option>
                                                <option value="2">2</option>
                                                <option value="3">3</option>
                                                <option value="4">4</option>
                                                <option value="5">5</option>
                                            </select>
                                        </div>
                                    </div>

                                </div>
                                <br />
                                <button type="submit" class="btn  btn-outline-primary">
                                    <span class="text">Adicionar ao carrinho</span> <i class="fas fa-shopping-cart"> &nbsp;</i>
                                </button>

                            }
                        }

                        <a asp-action="Index" class="btn  btn-info">
                            <span class="text">Voltar</span>
                        </a>
                    </form>
                </article>
            </main>
        </div>
    </div>
</section>